name: CodeQL

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 5'

jobs:
  Analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: github/codeql-action/init@v1
      with:
        languages: javascript
        config-file: ./.github/codeql-config.yml
          
    - uses: actions/setup-node@v2.1.1
    - run: npm install
    # - run: npm run build
    # - run: npm run format
      
    - uses: github/codeql-action/analyze@v1
